import os
import pandas as pd
import yfinance as yf
from typing import List, Dict

DATA_DIR = "data_cache"
os.makedirs(DATA_DIR, exist_ok=True)


def process_multiple_tickers(
    tickers: List[str],
    period: str = "5y",
    interval: str = "1d"
) -> Dict[str, pd.DataFrame]:

    # Dictionary to store processed datasets for each ticker
    processed_dict = {}

    # Process each ticker individually
    for ticker in tickers:
        try:
            print(f"\nProcessing{ticker}")

            # Download historical stock data using yfinance
            df = yf.download(
                ticker,
                period=period,
                interval=interval,
                progress=False
            )

            # Flatten MultiIndex columns if generated by yfinance
            if isinstance(df.columns, pd.MultiIndex):
                df.columns = df.columns.get_level_values(0)

            # Capitalize column names for consistency
            df.columns = [str(c).capitalize() for c in df.columns]

            # Define the required OHLCV columns
            required_cols = ['Open', 'High', 'Low', 'Close', 'Volume']

            # Keep only the required OHLCV columns
            df = df[required_cols].copy()

            # Convert the index into datetime format
            df.index = pd.to_datetime(df.index)

            # Set the index name to Date
            df.index.name = 'Date'

            # Sort the data chronologically
            df = df.sort_index()

            # Remove rows where all values are missing
            df = df.dropna(how='all')

            # Fill missing values using forward fill and backward fill
            df = df.ffill().bfill()

            # Remove invalid rows with non-positive closing prices
            # or negative trading volume
            df = df[(df['Close'] > 0) & (df['Volume'] >= 0)]

            # Create a safe ticker name for the output filename
            safe_ticker = ticker.replace(".", "_").replace("^", "")

            # Create the output file path
            file_path = os.path.join(DATA_DIR, f"raw_{safe_ticker}.csv")

            # Save the processed dataset as a CSV file
            df.to_csv(file_path)

            # Store the processed DataFrame in the dictionary
            processed_dict[ticker] = df

            # Display information about the processed dataset
            print(
                f"  Successfully processed {ticker}: {len(df)} rows "
                f"({df.index.min().strftime('%Y-%m-%d')} to "
                f"{df.index.max().strftime('%Y-%m-%d')})."
            )

            # Display the location of the saved dataset
            print(f"  Saved raw dataset to: '{file_path}'")

        except Exception as e:
            # Display the error and continue processing the next ticker
            print(f"  Error processing '{ticker}': {e}")

    # Display the final processing summary
    print(f"\nCompleted Data Processing")

    # Return all successfully processed datasets
    return processed_dict



if __name__ == "__main__":
    target_tickers = ["CBA.AX", "BHP.AX", "NAB.AX", "CSL.AX", "WBC.AX"]
    datasets = process_multiple_tickers(
        tickers=target_tickers,
        period="5y",
        interval="1d"
    )